# \# <i> working with APIs

In [1]:
import requests
url = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(url)
res

In [9]:
json_data = res.json()
# json_data

In [11]:
# this json data to datagframe
import pandas as pd
df = pd.json_normalize(json_data["data"])
df.head()

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."

In [13]:
df = df[["id", "Title", "Year", "ISBN"]]
df.head()

   id        Title  Year               ISBN
0   1       Carrie  1974  978-0-385-08695-0
1   2  Salem's Lot  1975  978-0-385-00751-1
2   3  The Shining  1977  978-0-385-12167-5
3   4         Rage  1977  978-0-451-07645-8
4   5    The Stand  1978  978-0-385-12168-2