# \# Linear Regression

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# \# <i> Insurance dataset
## X feature are age, sex, bmi, children, smoker based on that predict charges

In [3]:
insurance_data = pd.read_csv("insurance.csv")
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
# visualization
# sns.scatterplot(data=insurance_data, x = "bmi", y = "charges", hue = "smoker
# plt.title("Bmi vs charges")

#feature engineering
X = insurance_data.drop(columns=["charges","region"])
y = insurance_data["charges"]

X["sex"] = X["sex"].map({"female":1, "male":0})
X["smoker"] = X["smoker"].map({"yes":1, "no":0})

In [ ]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [ ]:
# train model
model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
# evalute matrix
# R ^ 2 score
r2 = r2_score(y_test, y_pred)
print("R^2 score : " , r2)

In [ ]:
# adjested r square value
n = len(X_test)
p = len(X_test.columns)
adj_r2 = 1 - ((1-r2)*(n-1))/(n-p-1);
print("adjusted r2 score : ", adj_r2)

In [ ]:

# visualization of best fit line
sns.regplot(
    x=X_test["bmi"],
    y=y_pred,
    scatter=True,
    ci=None
)

plt.title("best fit line using regression plot")
plt.ylabel("charges (Rs)")
plt.show()

# ## study hour and marks of students

In [ ]:
study_hours = np.random.randint(1,11,1000).reshape(-1,1)
std_marks = (8 * study_hours + 15) + np.random.randint(-10,10,1000).reshape(-1,1)

In [ ]:
model = LinearRegression()
model.fit(study_hours, std_marks)

In [ ]:
pred_marks = model.predict(study_hours)

In [ ]:
sns.regplot(x=study_hours, y = pred_marks)
plt.grid()
plt.title("study hours vs marks of student");
plt.xlabel("study hours")
plt.ylabel("students marks")
plt.show()

# \# House Pricing

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [5]:
house_dataset = pd.read_csv("HousePricePrediction.csv")

In [ ]:
X = house_dataset.drop(columns=["SalePrice"])
y = house_dataset["SalePrice"]

#feature engineering

#one hot encoding
categorical_cols = [
    "MSZoning",
    "LotConfig",
    "BldgType",
    "Exterior1st"
]

X = pd.get_dummies(
    X,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

# cleaning data
X = X.fillna(X.mean(numeric_only=True))
y = y.fillna(y.mean())

In [ ]:
# train - test split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("r2 is : " , r2)

In [ ]:
new_house = X.iloc[[0]].copy()
predicted_price = model.predict(new_house)

print("actual price : ", y.iloc[0])
print("Predicted Sale Price:", predicted_price[0])

In [ ]:

# visualiztion
sns.regplot(
    x=X_test["LotArea"],
    y=y_pred,
    scatter=True,
    line_kws={"color":"green"}
)
plt.show()

In [ ]:
sns.regplot(
    x=X_test["TotalBsmtSF"],
    y=y_pred,
    scatter=True,
    line_kws={"color":"green"}
)
plt.show()

In [ ]:
plt.figure(figsize=(8,5))
sns.boxplot(x=house_dataset["BldgType"], y=house_dataset["SalePrice"])
plt.show()

# \# Feature Engineering

In [6]:
insurance_data = pd.read_csv("insurance.csv")
insurance_data.head()
df = insurance_data.copy()

In [7]:
# one-hot encoding for region column
df = pd.get_dummies(df,columns=["region"], drop_first=True, dtype=int)

# encoding 
df['sex'] = df['sex'].map({"female":0, "male":1})
df['smoker'] = df['smoker'].map({"yes":1, "no":0})

df.head()

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,1
1,18,1,33.770,1,0,1725.55230,0,1,0
2,28,1,33.000,3,0,4449.46200,0,1,0
3,33,1,22.705,0,0,21984.47061,1,0,0
4,32,1,28.880,0,0,3866.85520,1,0,0

## \# feature engineering in house pricing dataset
* multiple col at once

In [8]:
house_data = pd.read_csv("HousePricePrediction.csv")
house_data.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [9]:
# MSZoning, BldgType, Exterior1st, BsmtFinSF2 have categorical data and have categories need encoding to numerical data

categories_col = ["MSZoning", "BldgType", "Exterior1st", "BsmtFinSF2"]

house_data = pd.get_dummies(house_data, columns=categories_col, drop_first=True, dtype=int)

In [10]:
house_data.columns[house_data.isnull().sum() > 0]
house_data = house_data.fillna(house_data.mean(numeric_only=True))

In [11]:
## \# interaction features
df2 = df.copy()
df2.head()

,age,sex,bmi,children,smoker,charges,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,1
1,18,1,33.770,1,0,1725.55230,0,1,0
2,28,1,33.000,3,0,4449.46200,0,1,0
3,33,1,22.705,0,0,21984.47061,1,0,0
4,32,1,28.880,0,0,3866.85520,1,0,0

In [12]:
df2["age_smoker"] = df2["age"] * df2["smoker"]
df2["bmi_smoker"] = df2["bmi"] * df2["smoker"]

In [13]:
X = df2.drop(columns=["charges"])
y = df2["charges"]

X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.2, random_state = 42)
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("r2 score : " , r2)

r2 score :  0.865231697953168

# \## <h1> Overfitting & Underfitting

In [15]:
# underfit & overfit
# r2 for training data is low & r2  for testing is also low => underfit
# r2 for training data high r2 for testing is low -> overfit

In [18]:
y_train_pred = model.predict(X_train)
r2_train = r2_score(y_train, y_train_pred)

print("training data r2 : " , r2_train)
print("testing data r2 : " , r2)

training data r2 :  0.8340713711218875
testing data r2 :  0.865231697953168