# \# <i> Pandas </i>

In [1]:
import pandas as pd

In [7]:
info = {
    "name" : ["saurav", "karan", "mayank", "shivam"],
    "marks" : [99,97,94, 92]
}

df = pd.DataFrame(info)
df

     name  marks
0  saurav     99
1   karan     97
2  mayank     94
3  shivam     92

# \# Series

In [12]:
import pandas as pd
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1

In [23]:
s = pd.Series([1,2,3,4,5], index=["adam", "bob", "charlie", "denis", "eve"])
print(s)
print(s["bob"])
print(s[1])
print(s.index)

adam       1
bob        2
charlie    3
denis      4
eve        5
dtype: int64
2
2
Index(['adam', 'bob', 'charlie', 'denis', 'eve'], dtype='object')

C:\Users\Dell\AppData\Local\Temp\ipykernel_17432\2736558035.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])

adam       1
bob        2
charlie    3
denis      4
dtype: int64

In [18]:
#vectorized operation
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])

print(s1 + s2)

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [20]:
s = pd.Series([1,2,3,4,5])
s[0] = 100
print(s)

#drop
changed_s = s1.drop(0)
print(changed_s)
print(s)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

# \# Dataframe

In [28]:
# dataframe creation using dictionary
info = {
    "name" : ["adam", "bob", "eve"],
    "age" : [23,24,25],
    "gpa" : [9.5, 9.7,9.4]
}

df = pd.DataFrame(info)
print(df)
print(df.index) # row labels
print(df.columns) # col labels

   name  age  gpa
0  adam   23  9.5
1   bob   24  9.7
2   eve   25  9.4
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'gpa'], dtype='object')

In [29]:
# datagram using list of list
df = pd.DataFrame([["Adam", 45], ["Bob", 23]], columns=["name", "age"])
df

   name  age
0  Adam   45
1   Bob   23

In [32]:
# dataframe using numpy array
import numpy as np

np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr, columns=["a", "b", "c"])
df

   a  b  c
0  1  2  3
1  4  5  6